---
title: Blokkenhuis
hero_image: images/banner.png
description: Leer hoe je objecten kunt bewerken en uitbouwen in Blender door een huis uit één blok te maken
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-02-01
steps:
  - 
    title: Inleiding
  - 
    title: Hoekpunten, randen en vlakken
  - 
    title: Maak een half dak
    completion:
      - engaged
  - 
    title: Uitbouwen
  - 
    title: Maak de andere helft van het dak
    completion:
      - internal
  - 
    title: 'Uitdaging: kleur je huis in'
