---
title: Block house
hero_image: images/banner.png
description: Create a house from a single block, using Blender
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2025-01-30
steps:
- title: Introduction
- title: Corners, edges and faces
- title: Create half a roof
  completion:
  - engaged
- title: Extrude
- title: Create the other half of the roof
  completion:
  - internal
- title: 'Challenge: colour in your house'
  completion:
  - external
