---
title: ब्लॉक हाउस
hero_image: images/banner.png
description: केवल एक block से घर बनाकर वस्तुओं को संपादित करने और Blender में निकालने
  का तरीका सीखें।
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-02-01
steps:
- title: परिचय
- title: सिरे, किनारे और चेहरे
- title: आधी छत बनाएँ.
  completion:
  - engaged
- title: बाहर निकाल लीजिये
- title: छत का दूसरा आधा हिस्सा बनाएँ
  completion:
  - internal
- title: 'चुनौती: अपने घर को रंग दें'
