---
title: ब्लॉक हाउस
hero_image: images/banner.png
description: किसी एक ब्लॉक से एक घर बनाकर वस्तुओं को संपादित करने और Blender में निकालने का तरीका सीखें।
theme: turquoise #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-02-01
steps:
  - 
    title: भूमिका
  - 
    title: Vertices, edges and faces
  - 
    title: Create half a roof
  - 
    title: Extrude
  - 
    title: Create the other half of the roof
  - 
    title: "Challenge: colour in your house"
