---
title: Block house
hero_image: images/banner.png
description: Learn how to edit objects and extrude in Blender by creating a house from a single block
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-02-01
steps:
  - 
    title: Introduction
  - 
    title: Vertices, edges and faces
  - 
    title: Create half a roof
    completion:
      - engaged
  - 
    title: Extrude
  - 
    title: Create the other half of the roof
    completion:
      - internal
  - 
    title: 'Challenge: colour in your house'
