---
title: Casa de bloques
hero_image: images/banner.png
description: Aprende a editar objetos y extraerlos en Blender creando una casa desde un simple bloque
theme: turquoise #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-02-01
steps:
  - 
    title: Introducción
  - 
    title: Vertices, edges and faces
  - 
    title: Create half a roof
  - 
    title: Extrude
  - 
    title: Create the other half of the roof
  - 
    title: "Desafío: colorea tu casa"
