---
title: Casa de bloques
hero_image: images/banner.png
description: Aprende a editar objetos y a extraerlos en Blender creando una casa desde un simple bloque
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-02-01
steps:
  - title: Introducción
  - title: Vértices, bordes y caras
  - title: Crea la mitad de un techo
    completion:
      - engaged
  - title: Extruir
  - title: Crea la otra mitad del techo
    completion:
      - internal
  - title: 'Desafío: colorea tu casa'
